version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: all_in_one_web
    command: sh -c ./entrypoint.sh
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: all_in_one_redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: all_in_one_celery
    command: celery -A config worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env
    networks:
      - app_network

volumes:
  static_volume:
  media_volume:

networks:
  app_network:
    driver: bridge
